export const CHANGE_ALL_TOP_LIST = "ranking/CHANGE_ALL_TOP_LIST"
export const CHANGE_CURRENT_INDEX = "ranking/CHANGE_CURRENT_INDEX"
export const CHANGE_CURRENT_PLAY_LIST = "ranking/CHANGE_CURRENT_PLAY_LIST"
export const CHANGE_SCROLL_HEIGHT = "ranking/CHANGE_SCROLL_HEIGHT"