export const CHANGE_HOT_ALBUM_LIST = "album/CHANGE_HOT_ALBUM_LIST"
export const CHANGE_TOP_ALBUM_LIST = "album/CHANGE_TOP_ALBUM_LIST"
export const CHANGE_CURRENT_PAGE = "album/CHANGE_CURRENT_PAGE"
export const CHANGE_TOP_TOTAL_COUNT = "album/CHANGE_TOP_TOTAL_COUNT"