export const CHANGE_ALL_CATEGORY = "playlist/CHANGE_ALL_CATEGORY"
export const CHANGE_CURRENT_CATEGORY = "playlist/CHANGE_CURRENT_CATEGORY"
export const CHANGE_CURRENT_PLAY_LIST = "playlist/CHANGE_CURRENT_PLAY_LIST"
export const CHANGE_CURRENT_PAGE = "playlist/CHANGE_CURRENT_PAGE"