export const CHANGE_CATE_LIST = "djradio/CHANGE_CATE_LIST"
export const CHANGE_RECOMMEND_LIST = "djradio/CHANGE_RECOMMEND_LIST"
export const CHANGE_RADIO_LIST = "djradio/CHANGE_RADIO_LIST"
export const CHANGE_CURRENT_CAT_ID = "djradio/CHANGE_CURRENT_CAT_ID"